#name: inception

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - backend
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DB}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_ADMIN_USER: ${WP_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WORDPRESS_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WORDPRESS_USER2: ${WP_USER1_USER}
      WORDPRESS_USER2_EMAIL: ${WP_USER1_EMAIL}
      WORDPRESS_USER2_PASSWORD_FILE: /run/secrets/wp_user1_password
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
    secrets:
      - db_password
      - wp_admin_password
      - wp_keys
      - wp_user1_password

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      - backend
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html:ro
      - ../secrets/certs:/etc/ssl/certs:ro
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

volumes:
  # Named volumes without bind mounts
  db_data:
    driver: local
  wp_files:
    driver: local
  
  # Named volumes with bind mounts stored in /home/pgrellie/data/
  # db_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/pgrellie/data/mariadb
  # wp_files:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/pgrellie/data/wordpress

networks:
  backend:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_keys:
    file: ../secrets/wp_keys.txt
  wp_user1_password:
    file: ../secrets/wp_user1_password.txt