services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - backend
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DB}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_ADMIN_USER: ${WP_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WORDPRESS_USER2: ${WP_USER1_USER}
      WORDPRESS_USER2_EMAIL: ${WP_USER1_EMAIL}
      WORDPRESS_USER2_PASSWORD: ${WP_USER1_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      - backend
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html:ro
      - ./secrets/certs:/etc/ssl/certs:ro
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pgrellie/data/mariadb
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pgrellie/data/wordpress

networks:
  backend:
    driver: bridge